# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: harness/reasoning/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'harness/reasoning/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!harness/reasoning/v1/common.proto\x12\x14harness.reasoning.v1\")\n\x0f\x43ontractVersion\x12\x16\n\x0eschema_version\x18\x01 \x01(\tBJZHgithub.com/Standard-Syntax/basic/go/gen/harness/reasoning/v1;reasoningv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'harness.reasoning.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZHgithub.com/Standard-Syntax/basic/go/gen/harness/reasoning/v1;reasoningv1'
  _globals['_CONTRACTVERSION']._serialized_start=59
  _globals['_CONTRACTVERSION']._serialized_end=100
# @@protoc_insertion_point(module_scope)
