# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: harness/reasoning/v1/planning.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'harness/reasoning/v1/planning.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from harness_agents._generated.harness.reasoning.v1 import common_pb2 as harness_dot_reasoning_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#harness/reasoning/v1/planning.proto\x12\x14harness.reasoning.v1\x1a!harness/reasoning/v1/common.proto\"=\n\x0fRepositoryEntry\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x0e\n\x06sha256\x18\x03 \x01(\t\"\x81\x03\n\x13TaskPlanningRequest\x12@\n\x08\x65nvelope\x18\x01 \x01(\x0b\x32..harness.reasoning.v1.ReasoningRequestEnvelope\x12!\n\x19\x61pproved_specification_id\x18\x10 \x01(\t\x12%\n\x1d\x61pproved_specification_digest\x18\x11 \x01(\t\x12=\n\x0erepository_map\x18\x12 \x03(\x0b\x32%.harness.reasoning.v1.RepositoryEntry\x12\x16\n\x0ereadable_paths\x18\x13 \x03(\t\x12\x16\n\x0ewritable_paths\x18\x14 \x03(\t\x12\x18\n\x10prohibited_paths\x18\x15 \x03(\t\x12\x18\n\x10task_count_limit\x18\x16 \x01(\r\x12\x19\n\x11parallelism_limit\x18\x17 \x01(\r\x12 \n\x18\x61\x63\x63\x65ptance_criterion_ids\x18\x18 \x03(\t\"!\n\x0eTaskDependency\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"\xab\x02\n\x0bPlannedTask\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\tobjective\x18\x02 \x01(\t\x12:\n\x0c\x64\x65pendencies\x18\x03 \x03(\x0b\x32$.harness.reasoning.v1.TaskDependency\x12 \n\x18\x61\x63\x63\x65ptance_criterion_ids\x18\x04 \x03(\t\x12\x16\n\x0ereadable_paths\x18\x05 \x03(\t\x12\x16\n\x0ewritable_paths\x18\x06 \x03(\t\x12\x18\n\x10prohibited_paths\x18\x07 \x03(\t\x12\x1b\n\x13\x65xclusive_resources\x18\x08 \x03(\t\x12\x1a\n\x12required_check_ids\x18\t \x03(\t\x12\x17\n\x0fstop_conditions\x18\n \x03(\t\"\x82\x02\n\x11TaskGraphProposal\x12\x38\n\x08identity\x18\x01 \x01(\x0b\x32&.harness.reasoning.v1.ProposalIdentity\x12!\n\x19\x61pproved_specification_id\x18\x10 \x01(\t\x12%\n\x1d\x61pproved_specification_digest\x18\x11 \x01(\t\x12\x30\n\x05tasks\x18\x12 \x03(\x0b\x32!.harness.reasoning.v1.PlannedTask\x12\x13\n\x0b\x61ssumptions\x18\x13 \x03(\t\x12\"\n\x1aunresolved_scope_questions\x18\x14 \x03(\tBJZHgithub.com/Standard-Syntax/basic/go/gen/harness/reasoning/v1;reasoningv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'harness.reasoning.v1.planning_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZHgithub.com/Standard-Syntax/basic/go/gen/harness/reasoning/v1;reasoningv1'
  _globals['_REPOSITORYENTRY']._serialized_start=96
  _globals['_REPOSITORYENTRY']._serialized_end=157
  _globals['_TASKPLANNINGREQUEST']._serialized_start=160
  _globals['_TASKPLANNINGREQUEST']._serialized_end=545
  _globals['_TASKDEPENDENCY']._serialized_start=547
  _globals['_TASKDEPENDENCY']._serialized_end=580
  _globals['_PLANNEDTASK']._serialized_start=583
  _globals['_PLANNEDTASK']._serialized_end=882
  _globals['_TASKGRAPHPROPOSAL']._serialized_start=885
  _globals['_TASKGRAPHPROPOSAL']._serialized_end=1143
# @@protoc_insertion_point(module_scope)
