# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: harness/reasoning/v1/specification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'harness/reasoning/v1/specification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from harness_agents._generated.harness.reasoning.v1 import common_pb2 as harness_dot_reasoning_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(harness/reasoning/v1/specification.proto\x12\x14harness.reasoning.v1\x1a!harness/reasoning/v1/common.proto\"\x8e\x02\n\x14SpecificationRequest\x12@\n\x08\x65nvelope\x18\x01 \x01(\x0b\x32..harness.reasoning.v1.ReasoningRequestEnvelope\x12\x19\n\x11problem_statement\x18\x10 \x01(\t\x12\x17\n\x0f\x64\x65sired_outcome\x18\x11 \x01(\t\x12\x19\n\x11known_constraints\x18\x12 \x03(\t\x12\x17\n\x0fknown_non_goals\x18\x13 \x03(\t\x12\x14\n\x0cstakeholders\x18\x14 \x03(\t\x12\x1f\n\x12repository_summary\x18\x15 \x01(\tH\x00\x88\x01\x01\x42\x15\n\x13_repository_summary\"]\n\x13\x41\x63\x63\x65ptanceCriterion\x12\x14\n\x0c\x63riterion_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x1b\n\x13verification_method\x18\x03 \x01(\t\"M\n\x11SpecificationRisk\x12\x0f\n\x07risk_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\nmitigation\x18\x03 \x01(\t\"P\n\x15SpecificationQuestion\x12\x13\n\x0bquestion_id\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\x12\x10\n\x08\x62locking\x18\x03 \x01(\x08\"\xfb\x02\n\x15SpecificationProposal\x12\x38\n\x08identity\x18\x01 \x01(\x0b\x32&.harness.reasoning.v1.ProposalIdentity\x12\r\n\x05title\x18\x10 \x01(\t\x12\x0c\n\x04goal\x18\x11 \x01(\t\x12\x0e\n\x06\x61\x63tors\x18\x12 \x03(\t\x12\x13\n\x0b\x63onstraints\x18\x13 \x03(\t\x12\x11\n\tnon_goals\x18\x14 \x03(\t\x12\x46\n\x13\x61\x63\x63\x65ptance_criteria\x18\x15 \x03(\x0b\x32).harness.reasoning.v1.AcceptanceCriterion\x12\x13\n\x0b\x61ssumptions\x18\x16 \x03(\t\x12\x36\n\x05risks\x18\x17 \x03(\x0b\x32\'.harness.reasoning.v1.SpecificationRisk\x12>\n\tquestions\x18\x18 \x03(\x0b\x32+.harness.reasoning.v1.SpecificationQuestionBJZHgithub.com/Standard-Syntax/basic/go/gen/harness/reasoning/v1;reasoningv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'harness.reasoning.v1.specification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZHgithub.com/Standard-Syntax/basic/go/gen/harness/reasoning/v1;reasoningv1'
  _globals['_SPECIFICATIONREQUEST']._serialized_start=102
  _globals['_SPECIFICATIONREQUEST']._serialized_end=372
  _globals['_ACCEPTANCECRITERION']._serialized_start=374
  _globals['_ACCEPTANCECRITERION']._serialized_end=467
  _globals['_SPECIFICATIONRISK']._serialized_start=469
  _globals['_SPECIFICATIONRISK']._serialized_end=546
  _globals['_SPECIFICATIONQUESTION']._serialized_start=548
  _globals['_SPECIFICATIONQUESTION']._serialized_end=628
  _globals['_SPECIFICATIONPROPOSAL']._serialized_start=631
  _globals['_SPECIFICATIONPROPOSAL']._serialized_end=1010
# @@protoc_insertion_point(module_scope)
